# Generated by Django 5.1.3 on 2024-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_descripcion_perfilusuario_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
