# Generated by Django 5.1.3 on 2024-12-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='url',
        ),
    ]
