# Generated by Django 5.1.3 on 2024-12-04 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_perfilusuario_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.CharField(choices=[('color_favorito', 'Color favorito'), ('auto_favorito', 'Auto favorito'), ('segundo_nombre_papa_mama', 'Segundo nombre de papá/mamá'), ('pelicula_favorita', 'Película favorita')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Preg_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntas')),
            ],
        ),
    ]
